name: Lei Hooks CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Install lei-hooks deps
        run: |
          npm i
          npm run bootstrap
        env:
          CI: true
      - name: Build core package
        run: |
          cd ./packages/hooks
          gulp
      - name: Commit changes
        run: |
          git config credential.helper 'cache --timeout=120'
          git config --global user.name "bigbigDreamer"
          git config --global user.email "jadeface.scholar@gmail.com"
          git add .
          git commit --allow-empty -m 'commit gulp is generate'
          git push -q https://${DOCS_GITHUB_TOKEN}@github.com/bigbigDreamer/lei-hooks.git
      - name: Add npm token
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Commit changes
        run: |
            git add .
            git commit --allow-empty -m 'commit .npmrc'
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/bigbigDreamer/lei-hooks.git

      - name: Lerna publish
        run: |
          lerna publish patch --yes
