name: Lei Hooks CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Install lei-hooks deps
        run: |
          npm i
          npm run bootstrap
        env:
          CI: true
      - name: Build core package
        run: |
          cd ./packages/hooks
          gulp
      - name: Commit changes
        run: |
          git add .
          git commit -m "feat: commit gulp's generate"
          git push
      - name: Lerna publish
        run: |
          lerna publish patch --yes
