name: Lei Hooks CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Del npmrc
        run: |
          rm -rf ./.npmrc
      - name: Authenticate with Registry
        run: |
          cat >> ./.npmrc <<EOF
          registry=https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
          EOF
#           echo "registry=https://registry.npmjs.org/" > ./.npmrc
#          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ./.npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install lei-hooks deps
        run: |
          npm i
          cd ./packages/hooks
          npm i
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build core package
        run: |
          cd ./packages/hooks
          gulp
      - name: Commit changes
        run: |
          git config credential.helper 'cache --timeout=120'
          git config --global user.name "bigbigDreamer"
          git config --global user.email "jadeface.scholar@gmail.com"
          git add .
          git commit --allow-empty -m 'feat: commit gulp is generate'
          git push -q https://${DOCS_GITHUB_TOKEN}@github.com/bigbigDreamer/lei-hooks.git
          npm set unsafe-perm true -g
          npm set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN} -g
          npm set username ${NPM_USERNAME} -g
          npm set email ${NPM_EMAIL} -g

      - name: Lerna publish
        run: |
          cat ./.npmrc
          lerna publish patch --yes
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Reset npmrc
        run: |
          rm -rf ./.npmrc
          git add .
          git commit --allow-empty -m 'feat: rm -rf npmrc'
          git push -q https://${DOCS_GITHUB_TOKEN}@github.com/bigbigDreamer/lei-hooks.git
