name: Lei Hooks CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Node Version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Prepare npm and git
        run: |
          git config credential.helper 'cache --timeout=120'
          git config --global user.name "bigbigDreamer"
          git config --global user.email "jadeface.scholar@gmail.com"

      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install lei-hooks deps
        run: |
          npm i
          cd ./packages/hooks
          npm i
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Build core package
        run: |
          cd ./packages/hooks
          gulp
      - name: Commit changes
        run: |
          git add .
          git commit --allow-empty -m 'feat: commit gulp is generate'
          git push -q https://${DOCS_GITHUB_TOKEN}@github.com/bigbigDreamer/lei-hooks.git

      - name: Lerna publish
        run: |
          lerna clean --yes
          lerna bootstrap
          lerna publish patch --yes
